# Copyright (c) 2024, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

---
networks:
  quickstart:
    external: true
    name: ${DOCKER_NETWORK}

services:
  canton-console-app-provider:
    image: "${IMAGE_REPO}canton:${IMAGE_TAG}"
    volumes:
      - ../../config/canton-console/app.conf:/app/app.conf
      - ../../docker/canton-console/entrypoint.sh:/app/entrypoint.sh
    environment:
      - PARTICIPANT_LEDGER_API_PORT=${PARTICIPANT_LEDGER_API_PORT}
      - PARTICIPANT_ADMIN_API_PORT=${PARTICIPANT_ADMIN_API_PORT}
      - LEDGER_API_ADDRESS=participant-app-provider
      - CLIENT_ID=app-provider-unsafe
      - USERNAME=${AUTH_APP_PROVIDER_PARTICIPANT_ADMIN_USER_NAME}
      - PASSWORD=${AUTH_APP_PROVIDER_PARTICIPANT_ADMIN_USER_PASSWORD}
      - TOKEN_URL=${AUTH_APP_PROVIDER_TOKEN_URL}
    entrypoint: /app/entrypoint.sh
    stdin_open: true
    tty: true
    networks:
      - ${DOCKER_NETWORK}

  canton-console-app-user:
    image: "${IMAGE_REPO}canton:${IMAGE_TAG}"
    volumes:
      - ../../config/canton-console/app.conf:/app/app.conf
      - ../../docker/canton-console/entrypoint.sh:/app/entrypoint.sh
    environment:
      - PARTICIPANT_LEDGER_API_PORT=${PARTICIPANT_LEDGER_API_PORT}
      - PARTICIPANT_ADMIN_API_PORT=${PARTICIPANT_ADMIN_API_PORT}
      - LEDGER_API_ADDRESS=participant-app-user
      - CLIENT_ID=app-user-unsafe
      - USERNAME=${AUTH_APP_USER_PARTICIPANT_ADMIN_USER_NAME}
      - PASSWORD=${AUTH_APP_USER_PARTICIPANT_ADMIN_USER_PASSWORD}
      - TOKEN_URL=${AUTH_APP_USER_TOKEN_URL}
    entrypoint: /app/entrypoint.sh
    stdin_open: true
    tty: true
    networks:
      - ${DOCKER_NETWORK}