services:
  await-onboarding-done:
    mem_limit: 32mb
  backend-service:
    mem_limit: 1g
    environment:
      _JAVA_OPTIONS: "-XX:+UseContainerSupport -XX:-UseCompressedOops"
  global-synchronizer:
    mem_limit: 2g
    environment:
      _JAVA_OPTIONS: "-XX:+UseContainerSupport -XX:-UseCompressedOops -XX:InitialRAMPercentage=70.0 -XX:MaxRAMPercentage=70.0"    
  nginx-app-provider:
    mem_limit: 32mb
  nginx-app-user:
    mem_limit: 32mb
  nginx-sv:
    mem_limit: 32mb
  oauth:
    mem_limit: 256mb
  participant-app-provider:
    mem_limit: 4g
    environment:
      _JAVA_OPTIONS: "-XX:+UseContainerSupport -XX:-UseCompressedOops"
  participant-app-user:
    mem_limit: 4g
    environment:
      _JAVA_OPTIONS: "-XX:+UseContainerSupport -XX:-UseCompressedOops"
  participant-sv:
    mem_limit: 4g
    environment:
      _JAVA_OPTIONS: "-XX:+UseContainerSupport -XX:-UseCompressedOops"
  postgres-splice:
    mem_limit: 512mb
  postgres-splice-app-provider:
    mem_limit: 512mb
  postgres-splice-app-user:
    mem_limit: 512mb
  postgres-splice-sv:
    mem_limit: 512mb
  pqs:
    mem_limit: 1g
    environment:
      _JAVA_OPTIONS: "-XX:+UseContainerSupport -XX:-UseCompressedOops"
  scan:
    mem_limit: 2g
    environment:
      _JAVA_OPTIONS: "-XX:+UseContainerSupport -XX:-UseCompressedOops"
  scan-web-ui:
    mem_limit: 256mb
  sv-app:
    mem_limit: 2g
    environment:
      _JAVA_OPTIONS: "-XX:+UseContainerSupport -XX:-UseCompressedOops"
  sv-web-ui:
    mem_limit: 512mb
  validator-app-provider:
    mem_limit: 2g
  validator-app-user:
    mem_limit: 2g
    environment:
      _JAVA_OPTIONS: "-XX:+UseContainerSupport -XX:-UseCompressedOops"
  validator-sv:
    mem_limit: 2g
    environment:
      _JAVA_OPTIONS: "-XX:+UseContainerSupport -XX:-UseCompressedOops"
  wallet-web-ui-app-provider:
    mem_limit: 256mb
  wallet-web-ui-app-user:
    mem_limit: 256mb
  wallet-web-ui-sv:
    mem_limit: 256mb