# Copyright (c) 2024, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

server:
  http_listen_address: 0.0.0.0
  http_listen_port: ${HTTP_LISTEN_PORT}

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:${OTLP_LISTEN_PORT}"

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

compactor:
  compaction:
    compaction_window: 1h
    max_block_bytes: 100_000_000
    block_retention: 1h
    compacted_block_retention: 10m

storage:
  trace:
    backend: local
    block:
      bloom_filter_false_positive: .05
      v2_index_downsample_bytes: 1000
      v2_encoding: zstd
    wal:
      path: /tmp/tempo/wal
      v2_encoding: snappy
    local:
      path: /tmp/tempo/blocks
    pool:
      max_workers: 100
      queue_depth: 10000

metrics_generator:
  storage:
    path: /tmp/tempo/metrics_gen
    remote_write:
      - url: "http://prometheus:${PROMETHEUS_PORT}/api/v1/write"
        send_exemplars: true

overrides:
  defaults:
    ingestion:
      rate_strategy: local
      rate_limit_bytes: 15000000
      burst_size_bytes: 20000000
      max_traces_per_user: 10000
      max_global_traces_per_user: 0
    read:
      max_bytes_per_tag_values_query: 5000000
    compaction:
      block_retention: 0s
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
    global:
      max_bytes_per_trace: 1000000
