{
 "title": "Caching",
 "tags": [
  "cache",
  "performance"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(daml_cache_size, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cache Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "daml_cache_size{namespace=\"$namespace\"}",
     "legendFormat": "[{{node}}] {{cache}}"
    }
   ]
  },
  {
   "title": "Cache Throughput (hits)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(daml_cache_hits{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "[{{node}}] {{cache}}"
    }
   ]
  },
  {
   "title": "Cache Throughput (misses)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(daml_cache_misses{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "[{{node}}] {{cache}}"
    }
   ]
  },
  {
   "title": "Cache Throughput (evictions)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(daml_cache_evictions{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "[{{node}}] {{cache}}"
    }
   ]
  },
  {
   "title": "Contract State Cache Update Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(namespace) (rate(daml_participant_api_execution_cache_contract_state_register_update_duration_seconds{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(namespace) (rate(daml_participant_api_execution_cache_contract_state_register_update_duration_seconds{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(namespace) (rate(daml_participant_api_execution_cache_contract_state_register_update_duration_seconds{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(namespace) (rate(daml_participant_api_execution_cache_contract_state_register_update_duration_seconds{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}