# Copyright (c) 2023, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
networks:
  quickstart:
    external: true
    name: ${DOCKER_NETWORK}

volumes:
  onboarding:

services:
  environment-init:
    extends:
      file: ${MODULES_DIR}/splice-onboarding/compose.yaml
      service: splice-onboarding
    container_name: environment-init
    volumes:
      - ./environment-init.sh:/app/scripts/on/integration-tests-environment-init.sh
      - .:/work
    entrypoint: [ "/entrypoint.sh", "--exit-on-finish" ]
    networks:
      - ${DOCKER_NETWORK}
    depends_on: !reset []

  integration-tests:
    build:
      context: docker
      args:
        PLAYWRIGHT_VERSION: v1.54.1-jammy
    environment:
      - DOCKER_RUN=true
    volumes:
      - .:/work
      - ./start.sh:/app/start.sh
      - ${MODULES_DIR}/splice-onboarding/docker/utils.sh:/app/utils.sh
      - ../docker/create-app-install-request/run.sh:/app/create-app-install-request.sh
    working_dir: /work
    network_mode: host
    command: /app/start.sh
    depends_on:
      - environment-init
