{
 "title": "JVM Metrics",
 "tags": [
  "jvm",
  "gc"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(jvm_cpu_time_seconds_total, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(jvm_cpu_time_seconds_total{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "query": "label_values(jvm_cpu_time_seconds_total{namespace=\"$namespace\", pod=~\"$pod\"}, container)"
   },
   {
    "name": "jvm",
    "query": "label_values(jvm_cpu_time_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}, job)"
   },
   {
    "name": "jvm_mempool",
    "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\", jvm_memory_pool_name!~\".*nmethods.*\"}, jvm_memory_pool_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPUs Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_cpu_count{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\"}",
     "legendFormat": "available"
    },
    {
     "expr": "jvm_cpu_recent_utilization_ratio{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\"} * jvm_cpu_count{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\"}",
     "legendFormat": "in-use"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(idelta(jvm_gc_duration_seconds_count{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\"}[$__rate_interval])) by(jvm_gc_name, job)",
     "legendFormat": "[{{job}}] {{jvm_gc_name}} (count)"
    },
    {
     "expr": "sum(idelta(jvm_gc_duration_seconds_sum{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\"}[$__rate_interval])) by(jvm_gc_name, job)",
     "legendFormat": "[{{job}}] {{jvm_gc_name}} (time)"
    },
    {
     "expr": "histogram_count(sum(rate(jvm_gc_duration_seconds{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\"}[$__rate_interval])) by(jvm_gc_name, job))",
     "legendFormat": "[{{job}}] {{jvm_gc_name}} (count)"
    },
    {
     "expr": "histogram_sum(sum(rate(jvm_gc_duration_seconds{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\"}[$__rate_interval])) by(jvm_gc_name, job))",
     "legendFormat": "[{{job}}] {{jvm_gc_name}} (time)"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_thread_count{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\"}",
     "legendFormat": "{{jvm_thread_state}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\", jvm_memory_type=\"heap\"}) by(jvm_memory_type)",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\", jvm_memory_type=\"heap\"}) by(jvm_memory_type)",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_limit_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\", jvm_memory_type=\"heap\"}) by(jvm_memory_type)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Non-heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\", jvm_memory_type=\"non_heap\"}) by(jvm_memory_type)",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\", jvm_memory_type=\"non_heap\"}) by(jvm_memory_type)",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_limit_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\", jvm_memory_type=\"non_heap\"}) by(jvm_memory_type)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Memory pool - $jvm_mempool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "repeat": "jvm_mempool",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\", jvm_memory_pool_name=\"$jvm_mempool\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\", jvm_memory_pool_name=\"$jvm_mempool\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "jvm_memory_limit_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\", jvm_memory_pool_name=\"$jvm_mempool\"}",
     "legendFormat": "max"
    },
    {
     "expr": "irate(jvm_memory_used_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", job=\"$jvm\", jvm_memory_pool_name=\"$jvm_mempool\"}[$__rate_interval])",
     "legendFormat": "allocated"
    }
   ]
  }
 ]
}