{
 "title": "Network Operation Center Health",
 "tags": [ "availability" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(daml_health_status, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Participant Received Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(status) (rate(daml_participant_api_indexer_events_total{namespace=\"$namespace\", event_type=\"transaction\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processed Events",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(daml_participant_api_indexer_events_total{namespace=\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{application_id}}:{{event_type}}"
      }
     ]
    },
    {
     "title": "Metered Events",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(daml_participant_api_indexer_metered_events_total{namespace=\"$namespace\"}[$__rate_interval])",
       "legendFormat": "{{application_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate | All gRPC Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(daml_grpc_server_handled_total{namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "all gRPC requests"
      }
     ]
    },
    {
     "title": "Return Code | All gRPC Requests",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "targets": [
      {
       "expr": "sum by(grpc_code) (rate(daml_grpc_server_handled_total{namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency | All gRPC Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by(namespace) (rate(daml_grpc_server_duration_seconds{namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum by(namespace) (rate(daml_grpc_server_duration_seconds{namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(namespace) (rate(daml_grpc_server_duration_seconds{namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(namespace) (rate(daml_grpc_server_duration_seconds{namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  },
  {
   "title": "Top 5 Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rejected Transactions | Top 5 Application IDs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(5, sum by(application_id) (rate(daml_participant_api_indexer_events_total{namespace=\"$namespace\", status=\"rejected\"}[$__rate_interval])))",
       "legendFormat": "{{application_id}}"
      }
     ]
    },
    {
     "title": "gRPC Errors | Top 5 Endpoints",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(5, sum by(grpc_service_name, grpc_method_name) (rate(daml_grpc_server_handled_total{namespace=\"$namespace\", grpc_code!=\"OK\"}[$__rate_interval])))",
       "legendFormat": "{{grpc_service_name}}:{{grpc_method_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "options": {
      "content": "# Detailed Dashboards\n\n* Events: [Received](/d/digital-asset-received-events) / [Metered](/d/digital-asset-metered-events)\n* [Components' Status](/d/digital-asset-health)\n* [gRPC Endpoints](/d/digital-asset-grpc-endpoints)\n* [TODO HTTP Endpoints](/d/TODO)\n* [JVM Metrics](/d/digital-asset-jvm-metrics)\n* [JVM Executor Services](/d/digital-asset-jvm-executor-services)"
     }
    },
    {
     "title": "Components' Status",
     "type": "status-history",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "targets": [
      {
       "expr": "daml_health_status{namespace=\"$namespace\"}",
       "legendFormat": "{{component}}"
      }
     ]
    },
    {
     "title": "JVM Garbage Collection",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(idelta(jvm_gc_duration_seconds_count{namespace=\"$namespace\"}[$__rate_interval])) by(jvm_gc_name, job)",
       "legendFormat": "[{{job}}] {{jvm_gc_name}} (count)"
      },
      {
       "expr": "sum(idelta(jvm_gc_duration_seconds_sum{namespace=\"$namespace\"}[$__rate_interval])) by(jvm_gc_name, job)",
       "legendFormat": "[{{job}}] {{jvm_gc_name}} (time)"
      },
      {
       "expr": "histogram_count(sum(rate(jvm_gc_duration_seconds{namespace=\"$namespace\"}[$__rate_interval])) by(jvm_gc_name, job))",
       "legendFormat": "[{{job}}] {{jvm_gc_name}} (count)"
      },
      {
       "expr": "histogram_sum(sum(rate(jvm_gc_duration_seconds{namespace=\"$namespace\"}[$__rate_interval])) by(jvm_gc_name, job))",
       "legendFormat": "[{{job}}] {{jvm_gc_name}} (time)"
      }
     ]
    }
   ]
  }
 ]
}