# Copyright (c) 2025, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: 0BSD

server:
  forward-headers-strategy: NATIVE
  # Review Error settings here and set acceptable values for production use.
  # This configuration is for development purposes.
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-path: always
    include-exception: true
  port: ${BACKEND_PORT}

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG
    com.digitalasset.quickstart.oauth.Interceptor: DEBUG
    org.springframework: ERROR
    org.springframework.security: DEBUG
#    org.springframework.security.web.FilterChainProxy: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'

ledger:
  application-id: ${AUTH_APP_PROVIDER_BACKEND_USER_ID:AppId}
  validator-uri: ${VALIDATOR_URI}

# Access to the application is restricted to authorized end users from organization (e.g. AppProvider, AppUser) registered as tenant.
# Backend service starts with a single AppProvider internal tenant. Additional tenant registration is available through
# the /admin/tenant-registrations endpoint.
application:
  tenants:
    AppProvider:
      tenantId: AppProvider
      partyId: ${APP_PROVIDER_PARTY}
      internal: true
