# Copyright (c) 2025, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: 0BSD

spring:
  security:
    oauth2:
      client:
        registration:
          AppProviderBackend-Participant:
            client-id: ${AUTH_APP_PROVIDER_BACKEND_TO_PARTICIPANT_CLIENT_ID}
            client-secret: ${AUTH_APP_PROVIDER_BACKEND_TO_PARTICIPANT_SECRET}
            authorization-grant-type: client_credentials
            provider: AppProviderBackend
          AppProvider:
            client-id: ${AUTH_APP_PROVIDER_BACKEND_OIDC_CLIENT_ID}
            client-name: ${AUTH_APP_PROVIDER_PARTY}
            authorization-grant-type: authorization_code
            scope: "openid"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: AppProvider
          AppUser:
            client-id: ${AUTH_APP_USER_BACKEND_OIDC_CLIENT_ID}
            client-name: ${AUTH_APP_USER_PARTY}
            authorization-grant-type: authorization_code
            scope: "openid"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: AppUser
        provider:
          AppProviderBackend:
            issuer-uri: ${AUTH_APP_PROVIDER_ISSUER_URL_BACKEND}
          AppProvider:
            issuer-uri: ${AUTH_APP_PROVIDER_ISSUER_URL}
          AppUser:
            issuer-uri: ${AUTH_APP_USER_ISSUER_URL}
application:
  tenants:
    Org1:
      walletUrl: ${ORG1_WALLET_URL:http://wallet.localhost:2000/}

server:
  forward-headers-strategy: NATIVE

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG
    com.digitalasset.quickstart.oauth.Interceptor: DEBUG
#    org.springframework.security.web.FilterChainProxy: TRACE
#    org.springframework.web.filter: TRACE
#    org:
#      springframework:
#        security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
