# Copyright (c) 2025, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: 0BSD

#spring:
#  profiles:
#    active: ${BACKEND_SERVICE_PROFILE:oauth2}

server:
  forward-headers-strategy: NATIVE

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG
    com.digitalasset.quickstart.oauth.Interceptor: DEBUG
    org.springframework: ERROR
    org.springframework.security: DEBUG
#    org.springframework.security.web.FilterChainProxy: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'

ledger:
  application-id: ${AUTH_APP_PROVIDER_BACKEND_USER_ID:AppId}
  validator-uri: "http://splice:3${VALIDATOR_ADMIN_API_PORT}/api/validator"

application:
  tenants:
    AppProvider:
      tenantId: AppProvider
      partyId: ${APP_PROVIDER_PARTY}
      internal: true
