# Copyright (c) 2025, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: 0BSD

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_APP_PROVIDER_ISSUER_URL}
      client:
        registration:
          AppProviderBackend:
            client-id: ${AUTH_APP_PROVIDER_BACKEND_CLIENT_ID}
            client-secret: ${AUTH_APP_PROVIDER_BACKEND_SECRET}
            authorization-grant-type: client_credentials
            provider: AppProviderBackend
          AppProvider:
            client-id: ${AUTH_APP_PROVIDER_BACKEND_OIDC_CLIENT_ID}
            client-name: AppProvider
            authorization-grant-type: authorization_code
            scope: "openid"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: AppProvider
        provider:
          AppProviderBackend:
            issuer-uri: ${AUTH_APP_PROVIDER_ISSUER_URL}
          AppProvider:
            issuer-uri: ${AUTH_APP_PROVIDER_ISSUER_URL}

application:
  tenants:
    AppProvider:
      tenantId: AppProvider
      partyId: ${AUTH_APP_PROVIDER_PARTY}
      internal: true

server:
  forward-headers-strategy: NATIVE

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG
    com.digitalasset.quickstart.oauth.Interceptor: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
