# Copyright (c) 2025, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: 0BSD

application:
  tenants:
    AppProvider:
      users:
        - pat

security.token-config:
    subject: "anyone"
    audience: ${AUTH_APP_PROVIDER_AUDIENCE}
    secret: "unsafe"

