# Copyright (c) 2025, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: 0BSD

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${security.issuer-url}
      client:
        registration:
          AppProviderBackend:
            client-id: ${AUTH_APP_PROVIDER_BACKEND_CLIENT_ID}
            client-secret: ${AUTH_APP_PROVIDER_BACKEND_SECRET}
            authorization-grant-type: client_credentials
            provider: AppProvider
          AppProvider:
            client-id: ${AUTH_APP_PROVIDER_BACKEND_OIDC_CLIENT_ID}
            client-name: ${application.tenants.AppProvider.tenantId}
            authorization-grant-type: authorization_code
            scope: "openid"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: AppProvider
        provider:
          AppProvider:
            issuer-uri: ${security.issuer-url}

security:
  issuer-url: ${AUTH_APP_PROVIDER_ISSUER_URL}
