# Copyright (c) 2023, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
x-vars:
  app-provider-auth-env: &app-provider-auth-env
    path: ${APP_PROVIDER_AUTH_ENV}
    required: false

  app-user-auth-env: &app-user-auth-env
    path: ${APP_USER_AUTH_ENV}
    required: false


services:
  integration-tests:
    image: mcr.microsoft.com/playwright:v1.51.0-jammy
    env_file:
      - .env
      - ${LOCALNET_ENV_DIR}/common.env
      - *app-provider-auth-env
      - *app-user-auth-env
    volumes:
      - "./integration-test:/work"
    working_dir: /work
    network_mode: host
    command: npx playwright test --output /tmp/ --reporter line
