{
 "title": "Participant Received Events",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(daml_participant_api_indexer_events_total, namespace)"
   },
   {
    "name": "participant",
    "query": "label_values(daml_participant_api_indexer_events_total{namespace=\"$namespace\"}, participant_id)"
   },
   {
    "name": "application",
    "query": "label_values(daml_participant_api_indexer_events_total{namespace=\"$namespace\", participant_id=~\"$participant\"}, application_id)"
   },
   {
    "name": "group_by",
    "label": "group by",
    "query": "participant_id : participant_id,application_id : application_id"
   }
  ]
 },
 "panels": [
  {
   "title": "Received Events - Increase",
   "type": "gauge",
   "description": "(e.g. transaction, package upload, party allocation)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by($group_by) (increase(daml_participant_api_indexer_events_total{namespace=\"$namespace\", participant_id=~\"$participant\", application_id=~\"$application\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Successful Events - Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by(${group_by:csv}, event_type) (rate(daml_participant_api_indexer_events_total{namespace=\"$namespace\", participant_id=~\"$participant\", application_id=~\"$application\", status=\"accepted\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Rejected Events - Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by(${group_by:csv}, event_type, grpc_code) (rate(daml_participant_api_indexer_events_total{namespace=\"$namespace\", participant_id=~\"$participant\", application_id=~\"$application\", status=\"rejected\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}