# Copyright (c) 2024, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:${PROMETHEUS_PORT}
    basicAuth: false
    editable: true
    isDefault: true
    version: 1
    jsonData:
      timeInterval: 10s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
