# Copyright (c) 2024, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: http://tempo:${TEMPO_PORT}
    basicAuth: false
    editable: true
    isDefault: false
    version: 1
    jsonData:
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        tags: [{ key: 'service.name', value: 'service' }]
        queries:
          - name: 'Rate'
            query: 'sum(rate(traces_spanmetrics_calls_total{span_name="$${__span.name}", $$__tags}[$$__rate_interval]))'
          - name: 'Error Rate'
            query: 'sum(rate(traces_spanmetrics_calls_total{span_name="$${__span.name}", status_code="STATUS_CODE_ERROR", $$__tags}[$$__rate_interval]))'
          - name: 'Duration (p90)'
            query: 'histogram_quantile(0.9, sum(rate(traces_spanmetrics_latency_bucket{span_name="$${__span.name}", $$__tags}[$$__rate_interval])) by (le))'
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        tags: [{ key: 'service.name', value: 'service_name' }]
        customQuery: true
        query: '{ $${__tags} } | trace_id="$${__span.traceId}" | label_format level=detected_level'
