# Copyright (c) 2025, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: 2.1

# the default pipeline parameters, which will be updated according to the results of the path-filtering orb in setup:
parameters:
  shared_enabled:
    type: boolean
    default: true

commands:
  nix:
    steps:
      - run:
          name: Nix preparation
          command: .circleci/scripts/nix_prep.sh
      - restore_cache:
          name: Nix restore cache
          keys:
            - nix-qs-{{ checksum "/home/circleci/nix/cache-keys/orb-version" }}-{{ checksum "/home/circleci/nix/cache-keys/nix-checksums" }}
            - nix-qs-{{ checksum "/home/circleci/nix/cache-keys/orb-version" }}
      - run:
          name: Nix Setup
          command: .circleci/scripts/nix_setup.sh
      - save_cache:
          name: Nix save cache
          key: nix-qs-{{ checksum "/home/circleci/nix/cache-keys/orb-version" }}-{{ checksum "/home/circleci/nix/cache-keys/nix-checksums" }}
          paths:
            - /home/circleci/.config/nix
            - /home/circleci/.local/state
            - /home/circleci/.nix-bashrc
            - /home/circleci/.nix-channels
            - /home/circleci/.nix-defexpr
            - /home/circleci/.nix-profile
            - /nix
