# Copyright (c) 2023, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

networks:
  quickstart:
    external: true
    name: ${DOCKER_NETWORK}

volumes:
  onboarding:

services:
  container:
    extends:
      file: ${MODULES_DIR}/splice-onboarding/compose.yaml
      service: splice-onboarding
    volumes:
      - ./run.sh:/app/scripts/on/create-app-install-request.sh
    entrypoint: [ "/entrypoint.sh", "--exit-on-finish" ]
    networks:
      - ${DOCKER_NETWORK}
    depends_on: !reset []
